### ISSUE TITLE
2 Logitech devices : mouse + keyboard, each one having its own dongle (Unifying & Bolt), only keyboard is OK

### ISSUE THREAD

**Issue by Scalpos** [jalmeroth/deskhopl#1]
Hello Jan. As I want to have multi-screens support, trying your alternative firmware, it seems only the keyboard is OK in my case, using v1.1 DeskHop board.
Same behaviour with inverted dongles.

As shown in shared screenshots, only 1 device is registered on each dongle.
![image](https://github.com/user-attachments/assets/1a372d46-6013-47a4-91cc-700f59718af1)
![image](https://github.com/user-attachments/assets/12273654-0293-4978-b1be-d942c181035e)

With same devices and Deskhop firmware 0.65, the mouse is usable.
Mouse device is a Unifying M590
Keyboard is Bolt Pebble Keys 2 K380s

Would you have any advices regarding how to remap the keys (and mouse's buttons) to my liking ?

**Comment by jalmeroth** [comment]
Hi @Scalpos,

thanks for raising the first issue in this repo! :sweat_smile: 

> Same behaviour with inverted dongles.

Switching dongles from port A to B and vise versa just made the keyboard work in both settings. Did I get this right?

Could you test if at least the mouse buttons work, but the mouse isn't moving?

To better understand what's going on, would you mind sharing the USB HID Descriptor of the "Unifying" dongle? You can use [usbhid-dump](https://github.com/DIGImend/usbhid-dump) or similar tools.

> Would you have any advices regarding how to remap the keys (and mouse's buttons) to my liking ?

As the project description says, this is not a copy of deskhop and I'm currently not planning to implement remapping. Sorry!

Regards,
Jan

**Comment by Scalpos** [comment]
> thanks for raising the first issue in this repo! 😅

You're very welcome, thank you for your feedback 😋
> Switching dongles from port A to B and vise versa just made the keyboard work in both settings. Did I get this right?

Indeed.
Mouse's buttons seem inactive/not recognized.

Here are the USB HID details I could get. Sorry about provided usbhid-dump's output, I can't figure what's related to the Unifying dongle, so I provided lsusb's output and Window's TDD [Thesycon USB Descriptor Dumper](https://www.thesycon.de/eng/usb_descriptordumper.shtml) as well :
**lsusb**
<pre>Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 27c6:530c Shenzhen Goodix Technology Co.,Ltd. Fingerprint Reader
Bus 001 Device 006: ID 0c45:671f Microdia Integrated_Webcam_HD
Bus 001 Device 007: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 015: ID 2a94:504d G2Touch Multi-Touch by G2TSP
Bus 001 Device 005: ID 1a40:0801 Terminus Technology Inc. USB 2.0 Hub
Bus 001 Device 003: ID 05dc:a01a Lexar Media, Inc. Echo
Bus 001 Device 010: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 018: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub</pre>
**usbhid-dump**
<pre>001:015:001:DESCRIPTOR         1728424306.233210
 06 FF 00 09 01 A1 01 85 80 09 80 15 00 26 FF 00
 75 08 95 3F B1 02 85 80 09 01 91 02 85 81 09 81
 15 00 26 FF 00 75 08 95 3F 81 02 09 01 75 08 B1
 02 C0

001:015:000:DESCRIPTOR         1728424306.234258
 05 0D 09 04 A1 01 85 01 09 22 A1 02 09 42 15 00
 25 01 75 01 95 01 81 02 95 07 81 03 75 08 09 51
 95 01 81 02 05 01 26 80 07 75 10 55 0E 65 11 09
 30 35 00 46 71 0D 81 02 26 38 04 46 8F 07 09 31
 81 02 05 0D C0 09 22 A1 02 09 42 15 00 25 01 75
 01 95 01 81 02 95 07 81 03 75 08 09 51 95 01 81
 02 05 01 26 80 07 75 10 55 0E 65 11 09 30 35 00
 46 71 0D 81 02 26 38 04 46 8F 07 09 31 81 02 05
 0D C0 09 22 A1 02 09 42 15 00 25 01 75 01 95 01
 81 02 95 07 81 03 75 08 09 51 95 01 81 02 05 01
 26 80 07 75 10 55 0E 65 11 09 30 35 00 46 71 0D
 81 02 26 38 04 46 8F 07 09 31 81 02 05 0D C0 09
 22 A1 02 09 42 15 00 25 01 75 01 95 01 81 02 95
 07 81 03 75 08 09 51 95 01 81 02 05 01 26 80 07
 75 10 55 0E 65 11 09 30 35 00 46 71 0D 81 02 26
 38 04 46 8F 07 09 31 81 02 05 0D C0 09 22 A1 02
 09 42 15 00 25 01 75 01 95 01 81 02 95 07 81 03
 75 08 09 51 95 01 81 02 05 01 26 80 07 75 10 55
 0E 65 11 09 30 35 00 46 71 0D 81 02 26 38 04 46
 8F 07 09 31 81 02 05 0D C0 09 22 A1 02 09 42 15
 00 25 01 75 01 95 01 81 02 95 07 81 03 75 08 09
 51 95 01 81 02 05 01 26 80 07 75 10 55 0E 65 11
 09 30 35 00 46 71 0D 81 02 26 38 04 46 8F 07 09
 31 81 02 05 0D C0 09 22 A1 02 09 42 15 00 25 01
 75 01 95 01 81 02 95 07 81 03 75 08 09 51 95 01
 81 02 05 01 26 80 07 75 10 55 0E 65 11 09 30 35
 00 46 71 0D 81 02 26 38 04 46 8F 07 09 31 81 02
 05 0D C0 09 22 A1 02 09 42 15 00 25 01 75 01 95
 01 81 02 95 07 81 03 75 08 09 51 95 01 81 02 05
 01 26 80 07 75 10 55 0E 65 11 09 30 35 00 46 71
 0D 81 02 26 38 04 46 8F 07 09 31 81 02 05 0D C0
 09 22 A1 02 09 42 15 00 25 01 75 01 95 01 81 02
 95 07 81 03 75 08 09 51 95 01 81 02 05 01 26 80
 07 75 10 55 0E 65 11 09 30 35 00 46 71 0D 81 02
 26 38 04 46 8F 07 09 31 81 02 05 0D C0 09 22 A1
 02 09 42 15 00 25 01 75 01 95 01 81 02 95 07 81
 03 75 08 09 51 95 01 81 02 05 01 26 80 07 75 10
 55 0E 65 11 09 30 35 00 46 71 0D 81 02 26 38 04
 46 8F 07 09 31 81 02 05 0D C0 05 0D 55 0C 66 01
 10 47 FF FF 00 00 27 FF FF 00 00 95 01 75 10 09
 56 81 02 09 54 95 01 75 08 25 0A 81 02 85 02 09
 55 95 01 75 08 B1 02 C0

001:018:002:DESCRIPTOR         1728424306.236792
 06 00 FF 09 01 A1 01 85 10 95 06 75 08 15 00 26
 FF 00 09 01 81 00 09 01 91 00 C0 06 00 FF 09 02
 A1 01 85 11 95 13 75 08 15 00 26 FF 00 09 02 81
 00 09 02 91 00 C0 06 00 FF 09 04 A1 01 85 20 95
 0E 75 08 15 00 26 FF 00 09 41 81 00 09 41 91 00
 85 21 95 1F 09 42 81 00 09 42 91 00 C0

001:018:001:DESCRIPTOR         1728424306.238403
 05 01 09 02 A1 01 85 02 09 01 A1 00 95 10 75 01
 15 00 25 01 05 09 19 01 29 10 81 02 95 02 75 0C
 16 01 F8 26 FF 07 05 01 09 30 09 31 81 06 95 01
 75 08 15 81 25 7F 09 38 81 06 95 01 05 0C 0A 38
 02 81 06 C0 C0 05 0C 09 01 A1 01 85 03 95 02 75
 10 15 01 26 FF 02 19 01 2A FF 02 81 00 C0 05 01
 09 80 A1 01 85 04 95 01 75 02 15 01 25 03 09 82
 09 81 09 83 81 00 75 06 81 03 C0 06 BC FF 09 88
 A1 01 85 08 95 01 75 08 15 01 26 FF 00 19 01 29
 FF 81 00 C0

001:018:000:DESCRIPTOR         1728424306.239430
 05 01 09 06 A1 01 95 08 75 01 15 00 25 01 05 07
 19 E0 29 E7 81 02 81 03 95 05 05 08 19 01 29 05
 91 02 95 01 75 03 91 01 95 06 75 08 15 00 26 FF
 00 05 07 19 00 2A FF 00 81 00 C0
</pre>

**TTD**
<pre>Information for device USB Receiver (VID=0x046D PID=0xC52B):

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0025
Current configuration value: 0x01
Number of open pipes: 3


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x046D	idVendor
0xC52B	idProduct
0x1211	bcdDevice
0x01	iManufacturer   "Logitech"
0x02	iProduct        "USB Receiver"
0x00	iSerialNumber
0x01	bNumConfigurations


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0054	wTotalLength   (84 bytes)
0x03	bNumInterfaces
0x01	bConfigurationValue
0x04	iConfiguration   "RQR12.11_B0032"
0xA0	bmAttributes   (Bus-powered Device, Remote-Wakeup)
0x31	bMaxPower      (98 mA)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x01	bInterfaceSubClass   
0x01	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x003B	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x08	bInterval         (8 frames)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x01	bInterfaceSubClass   
0x02	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0094	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x82	bEndpointAddress  (IN endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x02	bInterval         (2 frames)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x02	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x005D	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x83	bEndpointAddress  (IN endpoint 3)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0020	wMaxPacketSize    (1 x 32 bytes)
0x02	bInterval         (2 frames)

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "Logitech"
0x02   0x0409  "USB Receiver"
0x04   0x0409  "RQR12.11_B0032"

------------------------------

Connection path for device: 
Contrôleur d’hôte compatible xHCI USB
Root Hub
USB Receiver (VID=0x046D PID=0xC52B) Port: 3

Running on: Windows 10 or greater (Build Version 19045)

Brought to you by TDD v2.19.0, Dec  5 2023, 12:08:38

**TTD Clavier** 2024-10-08
Information for device USB Receiver (VID=0x046D PID=0xC548):

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0027
Current configuration value: 0x01
Number of open pipes: 4


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x40	bMaxPacketSize0   (64 bytes)
0x046D	idVendor
0xC548	idProduct
0x0503	bcdDevice
0x01	iManufacturer   "Logitech"
0x02	iProduct        "USB Receiver"
0x00	iSerialNumber
0x01	bNumConfigurations


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x006D	wTotalLength   (109 bytes)
0x04	bNumInterfaces
0x01	bConfigurationValue
0x04	iConfiguration   "MPR05.03_B0020"
0xA0	bmAttributes   (Bus-powered Device, Remote-Wakeup)
0x31	bMaxPower      (98 mA)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x01	bInterfaceSubClass   
0x01	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x003B	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x01	bInterfaceSubClass   
0x02	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x009E	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x82	bEndpointAddress  (IN endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x02	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0036	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x83	bEndpointAddress  (IN endpoint 3)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x03	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0111	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x01AD	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x84	bEndpointAddress  (IN endpoint 4)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "Logitech"
0x02   0x0409  "USB Receiver"
0x04   0x0409  "MPR05.03_B0020"

------------------------------

Connection path for device: 
Contrôleur d’hôte compatible xHCI USB
Root Hub
USB Receiver (VID=0x046D PID=0xC548) Port: 4

Running on: Windows 10 or greater (Build Version 19045)

Brought to you by TDD v2.19.0, Dec  5 2023, 12:08:38</pre>

**Comment by jalmeroth** [comment]
Hi there,

good job, thanks for all this info! The most interesting part is this I guess:

> **usbhid-dump**
> 
> 001:018:001:DESCRIPTOR         1728424306.238403
>  05 01 09 02 A1 01 85 02 09 01 A1 00 95 10 75 01
>  15 00 25 01 05 09 19 01 29 10 81 02 95 02 75 0C
>  16 01 F8 26 FF 07 05 01 09 30 09 31 81 06 95 01
>  75 08 15 81 25 7F 09 38 81 06 95 01 05 0C 0A 38
>  02 81 06 C0 C0 05 0C 09 01 A1 01 85 03 95 02 75
>  10 15 01 26 FF 02 19 01 2A FF 02 81 00 C0 05 01
>  09 80 A1 01 85 04 95 01 75 02 15 01 25 03 09 82
>  09 81 09 83 81 00 75 06 81 03 C0 06 BC FF 09 88
>  A1 01 85 08 95 01 75 08 15 01 26 FF 00 19 01 29
>  FF 81 00 C0

Let me put the parsed descriptor here for later reference:
```
0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
0x09, 0x02,        // Usage (Mouse)
0xA1, 0x01,        // Collection (Application)
0x85, 0x02,        //   Report ID (2)
0x09, 0x01,        //   Usage (Pointer)
0xA1, 0x00,        //   Collection (Physical)
0x95, 0x10,        //     Report Count (16)
0x75, 0x01,        //     Report Size (1)
0x15, 0x00,        //     Logical Minimum (0)
0x25, 0x01,        //     Logical Maximum (1)
0x05, 0x09,        //     Usage Page (Button)
0x19, 0x01,        //     Usage Minimum (0x01)
0x29, 0x10,        //     Usage Maximum (0x10)
0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0x95, 0x02,        //     Report Count (2)
0x75, 0x0C,        //     Report Size (12)
0x16, 0x01, 0xF8,  //     Logical Minimum (-2047)
0x26, 0xFF, 0x07,  //     Logical Maximum (2047)
0x05, 0x01,        //     Usage Page (Generic Desktop Ctrls)
0x09, 0x30,        //     Usage (X)
0x09, 0x31,        //     Usage (Y)
0x81, 0x06,        //     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
0x95, 0x01,        //     Report Count (1)
0x75, 0x08,        //     Report Size (8)
0x15, 0x81,        //     Logical Minimum (-127)
0x25, 0x7F,        //     Logical Maximum (127)
0x09, 0x38,        //     Usage (Wheel)
0x81, 0x06,        //     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
0x95, 0x01,        //     Report Count (1)
0x05, 0x0C,        //     Usage Page (Consumer)
0x0A, 0x38, 0x02,  //     Usage (AC Pan)
0x81, 0x06,        //     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              //   End Collection
0xC0,              // End Collection
0x05, 0x0C,        // Usage Page (Consumer)
0x09, 0x01,        // Usage (Consumer Control)
0xA1, 0x01,        // Collection (Application)
0x85, 0x03,        //   Report ID (3)
0x95, 0x02,        //   Report Count (2)
0x75, 0x10,        //   Report Size (16)
0x15, 0x01,        //   Logical Minimum (1)
0x26, 0xFF, 0x02,  //   Logical Maximum (767)
0x19, 0x01,        //   Usage Minimum (Consumer Control)
0x2A, 0xFF, 0x02,  //   Usage Maximum (0x02FF)
0x81, 0x00,        //   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection
0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
0x09, 0x80,        // Usage (Sys Control)
0xA1, 0x01,        // Collection (Application)
0x85, 0x04,        //   Report ID (4)
0x95, 0x01,        //   Report Count (1)
0x75, 0x02,        //   Report Size (2)
0x15, 0x01,        //   Logical Minimum (1)
0x25, 0x03,        //   Logical Maximum (3)
0x09, 0x82,        //   Usage (Sys Sleep)
0x09, 0x81,        //   Usage (Sys Power Down)
0x09, 0x83,        //   Usage (Sys Wake Up)
0x81, 0x00,        //   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
0x75, 0x06,        //   Report Size (6)
0x81, 0x03,        //   Input (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection
0x06, 0xBC, 0xFF,  // Usage Page (Vendor Defined 0xFFBC)
0x09, 0x88,        // Usage (0x88)
0xA1, 0x01,        // Collection (Application)
0x85, 0x08,        //   Report ID (8)
0x95, 0x01,        //   Report Count (1)
0x75, 0x08,        //   Report Size (8)
0x15, 0x01,        //   Logical Minimum (1)
0x26, 0xFF, 0x00,  //   Logical Maximum (255)
0x19, 0x01,        //   Usage Minimum (0x01)
0x29, 0xFF,        //   Usage Maximum (0xFF)
0x81, 0x00,        //   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection

// 148 bytes
```

**Comment by jalmeroth** [comment]
@Scalpos, would you mind to try this test build: https://github.com/jalmeroth/deskhopl/actions/runs/11262174801

Just download/extract the `artifact.zip` and copy the corresponding `.uf2` file to the picos as usual.

**Comment by Scalpos** [comment]
I'm glad to report the mouse is now functionnal 👌
Thank you very much 💛
FYI I suggested **hrvach** to [include a toggable mode to DeskHop](https://github.com/hrvach/deskhop/discussions/161#discussioncomment-10860842), similar to how DeskHop**L** works.
